name: Build & push workcell images

on:
  push:
    tags:
      - '*.*.*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/python3.8/Dockerfile
            image: weanalyze/workcell-app
            runtime: "python3.8"
          - dockerfile: ./docker/python3.9/Dockerfile
            image: weanalyze/workcell-app
            runtime: "python3.9"            
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          flavor: |
            latest=false 
          tags: |
            type=semver,prefix=${{ matrix.runtime }}-v,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ matrix.image }}:${{ matrix.runtime }}-latest
          labels: ${{ steps.meta.outputs.labels }}